# CMake generated Testfile for 
# Source directory: /home/smartmatic/workspace/vera/tests
# Build directory: /home/smartmatic/workspace/vera/tests
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(VeraStyle "/home/smartmatic/workspace/vera/src/vera++" "--error" "--root" "/home/smartmatic/workspace/vera" "/home/smartmatic/workspace/vera/src/structures/Tokens.cpp" "/home/smartmatic/workspace/vera/src/structures/SourceFiles.cpp" "/home/smartmatic/workspace/vera/src/structures/SourceLines.cpp" "/home/smartmatic/workspace/vera/src/structures/Statements.cpp" "/home/smartmatic/workspace/vera/src/main.cpp" "/home/smartmatic/workspace/vera/src/legacy_main.cpp" "/home/smartmatic/workspace/vera/src/plugins/Parameters.cpp" "/home/smartmatic/workspace/vera/src/plugins/Rules.cpp" "/home/smartmatic/workspace/vera/src/plugins/Reports.cpp" "/home/smartmatic/workspace/vera/src/plugins/RootDirectory.cpp" "/home/smartmatic/workspace/vera/src/plugins/Profiles.cpp" "/home/smartmatic/workspace/vera/src/plugins/Interpreter.cpp" "/home/smartmatic/workspace/vera/src/plugins/Transformations.cpp" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/cpptcl.cpp" "/home/smartmatic/workspace/vera/src/plugins/Exclusions.cpp" "/home/smartmatic/workspace/vera/src/boost_main.cpp" "/home/smartmatic/workspace/vera/src/structures/Tokens.h" "/home/smartmatic/workspace/vera/src/structures/SourceLines.h" "/home/smartmatic/workspace/vera/src/structures/SourceFiles.h" "/home/smartmatic/workspace/vera/src/structures/Statements.h" "/home/smartmatic/workspace/vera/src/config.h" "/home/smartmatic/workspace/vera/src/plugins/Transformations.h" "/home/smartmatic/workspace/vera/src/plugins/Exclusions.h" "/home/smartmatic/workspace/vera/src/plugins/Rules.h" "/home/smartmatic/workspace/vera/src/plugins/RootDirectory.h" "/home/smartmatic/workspace/vera/src/plugins/Reports.h" "/home/smartmatic/workspace/vera/src/plugins/Interpreter.h" "/home/smartmatic/workspace/vera/src/plugins/Profiles.h" "/home/smartmatic/workspace/vera/src/plugins/CurrentRule.h" "/home/smartmatic/workspace/vera/src/plugins/Parameters.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/cpptcl.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/dispatchers.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/conversions.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/constructors.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/methods.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/metahelpers.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/methods_v.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/callbacks_v.h" "/home/smartmatic/workspace/vera/src/plugins/cpptcl-1.1.4/details/callbacks.h")
ADD_TEST(NoRoot "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/NoRoot.cmake")
ADD_TEST(VeraRootEnvironment "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/VeraRootEnvironment.cmake")
SET_TESTS_PROPERTIES(VeraRootEnvironment PROPERTIES  ENVIRONMENT "VERA_ROOT=/home/smartmatic/workspace/vera")
ADD_TEST(VeraRootCurrentDirectory "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/VeraRootCurrentDirectory.cmake")
SET_TESTS_PROPERTIES(VeraRootCurrentDirectory PROPERTIES  WORKING_DIRECTORY "/home/smartmatic/workspace/vera")
ADD_TEST(VeraLegacy "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/VeraLegacy.cmake")
SET_TESTS_PROPERTIES(VeraLegacy PROPERTIES  ENVIRONMENT "VERA_LEGACY=ON;VERA_ROOT=/home/smartmatic/workspace/vera")
ADD_TEST(StdInNoArgs "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/StdInNoArgs.cmake")
ADD_TEST(InputsDash "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/InputsDash.cmake")
ADD_TEST(InputsFile "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/InputsFile.cmake")
ADD_TEST(ShortInputs "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortInputs.cmake")
ADD_TEST(StdInDash "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/StdInDash.cmake")
ADD_TEST(StandardReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/StandardReport.cmake")
ADD_TEST(ShortStandardReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortStandardReport.cmake")
ADD_TEST(VCReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/VCReport.cmake")
ADD_TEST(ShortVCReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortVCReport.cmake")
ADD_TEST(XMLReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/XMLReport.cmake")
ADD_TEST(ShortXMLReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortXMLReport.cmake")
ADD_TEST(CheckStyleReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/CheckStyleReport.cmake")
ADD_TEST(ShortCheckStyleReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortCheckStyleReport.cmake")
ADD_TEST(ShowRule "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShowRule.cmake")
ADD_TEST(ShortShowRule "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortShowRule.cmake")
ADD_TEST(Warning "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Warning.cmake")
ADD_TEST(ShortWarning "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortWarning.cmake")
ADD_TEST(WarningShowRule "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/WarningShowRule.cmake")
ADD_TEST(Error "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Error.cmake")
ADD_TEST(ErrorShowRule "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ErrorShowRule.cmake")
ADD_TEST(Quiet "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Quiet.cmake")
ADD_TEST(ShortQuiet "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortQuiet.cmake")
ADD_TEST(Summary "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Summary.cmake")
ADD_TEST(ShortSummary "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortSummary.cmake")
ADD_TEST(Version "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Version.cmake")
ADD_TEST(VersionLegacy "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/VersionLegacy.cmake")
ADD_TEST(AggregatedShortOptions "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/AggregatedShortOptions.cmake")
ADD_TEST(NoDuplicate "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/NoDuplicate.cmake")
ADD_TEST(ShortNoDuplicate "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortNoDuplicate.cmake")
ADD_TEST(Parameter "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Parameter.cmake")
ADD_TEST(ParameterInvalid "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ParameterInvalid.cmake")
ADD_TEST(ShortParameter "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortParameter.cmake")
ADD_TEST(Parameters "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Parameters.cmake")
ADD_TEST(Profile "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Profile.cmake")
ADD_TEST(ShortProfile "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ShortProfile.cmake")
ADD_TEST(Exclusions "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/Exclusions.cmake")
ADD_TEST(Help "/home/smartmatic/workspace/vera/src/vera++" "--help" "foo" "bar")
ADD_TEST(ShortHelp "/home/smartmatic/workspace/vera/src/vera++" "-h" "foo" "bar")
ADD_TEST(RuleF001 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleF001.cmake")
ADD_TEST(RuleL001 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleL001.cmake")
ADD_TEST(RuleL002 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleL002.cmake")
ADD_TEST(RuleL003 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleL003.cmake")
ADD_TEST(RuleL004 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleL004.cmake")
ADD_TEST(RuleL005 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleL005.cmake")
ADD_TEST(RuleL006 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleL006.cmake")
ADD_TEST(RuleT001 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT001.cmake")
ADD_TEST(RuleT002 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT002.cmake")
ADD_TEST(RuleT003 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT003.cmake")
ADD_TEST(RuleT004 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT004.cmake")
ADD_TEST(RuleT005 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT005.cmake")
ADD_TEST(RuleT006 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT006.cmake")
ADD_TEST(RuleT007 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT007.cmake")
ADD_TEST(RuleT008 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT008.cmake")
ADD_TEST(RuleT009 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT009.cmake")
ADD_TEST(RuleT010 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT010.cmake")
ADD_TEST(RuleT011 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT011.cmake")
ADD_TEST(RuleT012 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT012.cmake")
ADD_TEST(RuleT013 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT013.cmake")
ADD_TEST(RuleT014 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT014.cmake")
ADD_TEST(RuleT015 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT015.cmake")
ADD_TEST(RuleT016 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT016.cmake")
ADD_TEST(RuleT017 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT017.cmake")
ADD_TEST(RuleT018 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT018.cmake")
ADD_TEST(RuleT019 "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleT019.cmake")
ADD_TEST(RuleDUMP "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/RuleDUMP.cmake")
ADD_TEST(ErrorReport "/usr/bin/cmake" "-D" "VERA_PROGRAM:FILEPATH=/home/smartmatic/workspace/vera/src/vera++" "-P" "/home/smartmatic/workspace/vera/tests/ErrorReport.cmake")
SUBDIRS(python)
