message("Running: \"${VERA_PROGRAM}\" \"--root\" \"/home/smartmatic/workspace/vera\" \"--rule\" \"T002\" \"/home/smartmatic/workspace/vera/tests/T002.cpp\"")
execute_process(COMMAND "${VERA_PROGRAM}"
  "--root" "/home/smartmatic/workspace/vera" "--rule" "T002" "/home/smartmatic/workspace/vera/tests/T002.cpp"
  RESULT_VARIABLE ret
  OUTPUT_VARIABLE output
  ERROR_VARIABLE error
  )
message("return value: ${ret}")
message("---output---\n${output}---error----\n${error}------------")

set(fail OFF)
if(NOT ${ret} EQUAL 0)
  message("Invalid return code. Expected return code was 0.")
  set(fail ON)
endif()
if(NOT "${output}" STREQUAL "/home/smartmatic/workspace/vera/tests/T002.cpp:4: reserved name used for macro (incorrect use of underscore)
/home/smartmatic/workspace/vera/tests/T002.cpp:5: reserved name used for macro (incorrect use of underscore)
/home/smartmatic/workspace/vera/tests/T002.cpp:7: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:8: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:9: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:10: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:11: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:12: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:13: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:14: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:15: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:16: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:17: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:18: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:19: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:20: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:21: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:22: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:23: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:24: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:25: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:26: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:27: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:28: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:29: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:30: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:31: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:32: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:33: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:34: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:35: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:36: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:37: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:38: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:39: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:40: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:41: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:42: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:43: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:44: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:45: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:46: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:47: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:48: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:49: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:50: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:51: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:52: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:53: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:54: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:55: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:56: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:57: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:58: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:59: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:60: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:61: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:62: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:63: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:64: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:65: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:66: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:67: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:68: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:69: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:70: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:71: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:72: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:73: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:74: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:75: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:76: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:77: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:78: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:79: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:80: reserved name used for macro (keyword or alternative token redefined)
")
  message("Output mismatch. Expected content was:")
  message("/home/smartmatic/workspace/vera/tests/T002.cpp:4: reserved name used for macro (incorrect use of underscore)
/home/smartmatic/workspace/vera/tests/T002.cpp:5: reserved name used for macro (incorrect use of underscore)
/home/smartmatic/workspace/vera/tests/T002.cpp:7: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:8: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:9: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:10: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:11: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:12: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:13: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:14: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:15: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:16: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:17: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:18: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:19: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:20: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:21: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:22: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:23: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:24: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:25: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:26: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:27: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:28: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:29: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:30: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:31: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:32: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:33: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:34: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:35: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:36: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:37: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:38: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:39: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:40: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:41: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:42: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:43: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:44: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:45: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:46: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:47: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:48: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:49: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:50: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:51: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:52: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:53: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:54: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:55: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:56: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:57: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:58: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:59: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:60: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:61: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:62: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:63: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:64: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:65: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:66: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:67: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:68: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:69: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:70: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:71: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:72: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:73: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:74: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:75: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:76: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:77: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:78: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:79: reserved name used for macro (keyword or alternative token redefined)
/home/smartmatic/workspace/vera/tests/T002.cpp:80: reserved name used for macro (keyword or alternative token redefined)
---")
  set(fail ON)
endif()
if(NOT "${error}" STREQUAL "")
  message("Output mismatch. Expected content was:")
  message("---")
  set(fail ON)
endif()

if(fail)
  message(FATAL_ERROR "some errors occurred.")
endif()
