#!/usr/bin/tclsh
# This file defines the set of scripts (rules) that should be executed
# by default (if no specific profile is named when vera++ is launched).

set rules {
    F001

    L001
    L002
    L003
    L004
    L005
    L006

    T001
    T002
    T003
    T004
    T005
    T006
    T007
    T008
    T009
    T010
    T011
    T012
    T013
    T015
    T016
    T017
    T018
    T019
}
